New product popular adaptive
projectx-curtains/frontend pull request #10
Opened 2022-09-14 08:37 UTC by bynikitachel

2022-09-15 15:53 UTC, imma-fish-u requested changes

2022-09-15 15:53 UTC, imma-fish-u commented on src/components/Gallery/index.js
> +          <UsedButton
Try to use react-responsive library with mediaquery hook (I used this: const isTabletOrMobile = useMediaQuery({ query: "(max-width: 1200px)" }); ) and simple button component with if else statement. (isTabletOrMobile) ? Button primary.... : Button secondary

2022-09-15 15:53 UTC, imma-fish-u commented on src/components/Gallery/index.scss
> +    .gallery-container {
gallery__container would be better

2022-09-15 15:53 UTC, imma-fish-u commented on src/components/Gallery/index.scss
> +@media (max-width: 768px) {
we put media query inside of every selector and pls use variables I created for media query to stay in tune

2022-09-15 15:53 UTC, imma-fish-u commented on src/components/UsedButton/index.js
> +    setDesktop(window.innerWidth > 767)
so react responsive lib will ease your life and you don't have to write such code anymore

2022-09-15 15:53 UTC, imma-fish-u commented on src/components/WhyWeAreItem/index.js
> +          width="66pх"
pls give a classname to this img and move width and height in scss

2022-09-15 15:53 UTC, imma-fish-u commented on src/pages/home/sections/Popular/index.js
> +const Index = ({ popularData }) => {
Lets try nicer naming for component, index doesn't really say what is it about

2022-09-19 07:09 UTC, bynikitachel commented on src/components/Gallery/index.scss
> +    .gallery-container {
why?

2022-10-27 10:22 UTC, closed without merging