Catalog layout
projectx-curtains/frontend pull request #7
Opened 2022-09-06 13:58 UTC by sukhinakatie

Added Layout.js and Layout.scss files

Layout.js consists of CatalogCard.js components with different type assigned.

Difficulties for now:
-Responsivness of the catalog is absent
-Gradient hover effect as in UI kit absent

2022-09-07 13:18 UTC, sukhinakatie commented
This commit includes Banner.

2022-09-08 09:52 UTC, imma-fish-u requested changes
we'll be approved after small changes

2022-09-08 09:52 UTC, imma-fish-u commented on src/components/Catalog/index.scss
> +    }
1. check everywhere on white space line between styles (like here &__container and &__description{

2022-09-08 09:52 UTC, imma-fish-u commented on src/components/Catalog/index.scss
> +// sale
everywhere in the end of the file add also white space line pls

2022-09-08 15:17 UTC, imma-fish-u approved these changes

2022-10-27 10:22 UTC, closed without merging