Why we are
projectx-curtains/frontend pull request #8
Opened 2022-09-07 16:55 UTC by bynikitachel

TASK E-1, S-4, T-1

2022-09-08 07:06 UTC, imma-fish-u requested changes

2022-09-08 07:06 UTC, imma-fish-u commented on src/pages/home/sections/WhyWeAre/index.js
> +      <div className="why-we-are-container">
why-we-are__container

2022-09-08 07:06 UTC, imma-fish-u commented on src/pages/home/sections/WhyWeAre/index.js
> +          {items && items.map((item, i) => {
why-we-are__content

2022-09-08 08:19 UTC, imma-fish-u approved these changes

2022-09-08 20:33 UTC, EgorAntonovich requested changes

2022-09-08 20:33 UTC, EgorAntonovich commented on src/mockData/CarouselSliderData.js
> +    {
Is it really cool to contains links like hardcode?

2022-09-08 20:33 UTC, EgorAntonovich commented on src/mockData/NewProductData.js
> +    {
hardcode?

2022-09-08 20:33 UTC, EgorAntonovich commented on src/pages/home/index.js
> +    const descriptionTextWorks = 'Фото с комплектом "Кармен": в уютной квартире семьи Сергея и Татьяны не хватало акцентного элемента, который одновременно подчеркивал бы характер хозяев, а также укр
please contains const text in independent file

2022-09-08 20:33 UTC, EgorAntonovich commented on src/pages/home/index.scss
> +        // @include button('basic', 'primary');
why it is empty?

2022-09-08 20:33 UTC, EgorAntonovich commented on src/pages/home/sections/NewProducts/index.js
> +        headerText="Новинки"
are we really need to harcode this?

2022-09-08 20:33 UTC, EgorAntonovich commented on src/pages/home/sections/WhyWeAre/index.js
> +const items = [
What about contains const things in independent file?

2022-09-09 08:17 UTC, bynikitachel commented on src/pages/home/sections/NewProducts/index.js
> +        headerText="Новинки"
yes

2022-10-27 10:22 UTC, closed without merging